### ISSUE TITLE
Unsupported compression method on vu1Memory.bin and vu1MicroMem.bin

### ISSUE THREAD

**Issue by honestabelink** [chaoticgd/vutrace#2]
Under the `vudis Usage` section, you say "where vu0MicroMem.bin or vu1MicroMem.bin can be extracted from a PCSX2 save state."

What do you use to extract these. I've tried 7zip and unzip, both say unsupported compression.

Both debug and release builds are like this, but the save states work perfectly fine for the emulator.
Am I missing something? 

Another option would be to use the debugger to view some bytes of vu1 memory and data, them mem search for them in the process and dump.

Also great work excited to get into vu1 :)

I'm currently working on the Xenosaga series.
I reduced the micro-code down by removing animation, shadows, hud, alpha rendering path, as much as could and still got 8gb 🌊
Targeting their multi CLUT/palette texture rendering for characters. I can't, for the life of me, calculate it from just file formats and disassembly for the EE alone 💀

**Comment by chaoticgd** [comment]
You can just add `SavestateZstdCompression=disabled` to your PCSX2_vm.ini file as long as you're on a version newer than [this](https://github.com/PCSX2/pcsx2/pull/6530) or as using the Qt GUI.

> I reduced the micro-code down by removing animation, shadows, hud, alpha rendering path, as much as could and still got 8gb

I assume by this you mean you tried to do a trace with vutrace and it ended up being huge. This is probably because vutrace currently doesn't begin and end traces on vsync, instead using an extremely crude heuristic that just counts the number of DMA chains that have been sent to VPU1. I've found this works okay for the R&C games so I never bothered to fix it. It also means that the size of traces may vary wildly between runs. The relevant code is [here](https://github.com/chaoticgd/vutrace/blob/master/pcsx2_011d6bebfa15e077cfde91af14d3ae7e57d348ed.patch#L287).

**Comment by chaoticgd** [comment]
I've added a note to the readme about the zstd thing.

**Comment by chaoticgd** [comment]
Actually, I just checked and it seems like 8GB is a perfectly normal size for a vutrace dump (I had forgotten about details like this). This is because it just writes out the whole contents of VU1 data memory after every instruction is executed. My explanation above is accurate with regards to how vutrace works but it is likely not the cause of your problem.

**Comment by honestabelink** [comment]
Thanks, 7zip works just fine now.

> I assume by this you mean you tried to do a trace with vutrace and it ended up being huge.

No actually. Your `extremely crude heuristic` worked just fine for Xenosaga. Trace begins with a clear and then proceeds nicely till the character is fully rendered. Which is perfect for me.

Ran it a couple times and got, 1386, 1510, 1388 traces. Trace 11 always has an accompanying dump of the framebuffer, which is cleared. Rendered model parts showing up in the FB are closely related from run to run.

So i'd say it's pretty consistent. 👍 

Though my use case is pretty limited, and not a typical DMA/VU/GS load.

My goal was reducing everything to just the work I'm interested in analyzing. For example later when I work on the rigging there will be a different subset of the renderer I enable and trace. The trace size was no issue but I was still surprised.
But now that makes sense.

vudis use for me was just quickly dumping from CLI. 

_It should be noted to use a release build of pcsx2. Traces from debug are broken, only outputs .bin with a header and nothing else._

Thanks again for your help and the project. I'm off to crawl through your superswizzle code, cause again 💀😉.
